name: doh_client
description: DNS-over-HTTPS Client
version: 0.1.0
author: Skotnikov Sergei <skotnikov@europe.com>
homepage: https://github.com/bronjham-code/doh_client

environment:
  sdk: '>=2.8.1 <3.0.0'

#dependencies:

#dev_dependencies:
  #test: ^1.14.4
