name: doh_client
description: This implementation allows you to send requests to DNS-over-HTTPS services.
version: 0.2.0 # recommended verion bump in migration guide
author: Skotnikov Sergei <skotnikov@europe.com>
homepage: https://github.com/bronjham-code/doh_client

environment:
  sdk: '>=2.12.0 <3.0.0' #null safety on after 2.12.0

dependencies: 
  universal_io: ^2.0.4

#dev_dependencies:
  #test: ^1.14.4
